modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Piglin%20Names"
logoFile="icon.png"

[[mods]]
modId="piglinnames"
version="1.0"
displayName="Piglin Names"
displayURL="https://serilum.com/mod/piglin-names"
authors="Rick South"
description='''Gives all piglins a default or custom name to liven up the world.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Alister, Andrean Olgo, aternosorg, BirdieMiner, Cherriesaurus, Michael W. S., Shana Gitnick, Sukhmai, Tyler Behl   

If you would like to contribute too, check out https://serilum.com/donate. Appreciate it! <3   
'''

[[dependencies.piglinnames]]
    modId="collective"
    type="required"
    mandatory=true
    versionRange="[7.71,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.piglinnames]]
    modId="minecraft"
    type="required"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"