modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Piglin%20Names"
logoFile="icon.png"

[[mods]]
modId="piglinnames"
version="1.4"
displayName="Piglin Names"
displayURL="https://serilum.com/mod/piglin-names"
authors="Rick South"
description='''Gives all piglins a default or custom name to liven up the world.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Andrean Olgo, aternosorg, Cherriesaurus, Linda Jansen, Michelle Smith, MWS, Tyler Behl   

If you would like to contribute too, check out https://serilum.com/donate. Appreciate it! <3   
'''

[[dependencies.piglinnames]]
    modId="collective"
    mandatory=true
    versionRange="[8.25,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.piglinnames]]
    modId="minecraft"
    mandatory=true
    versionRange="[26.1.2]"
    ordering="NONE"
    side="BOTH"
